version: 2
updates:
  - package-ecosystem: composer
    directory: "/packages/php"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - erunion
    labels:
      - scope:dependency
      - area:php
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - scope:dependency
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - erunion
    labels:
      - scope:dependency
      - area:node
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: pip
    directory: "/packages/python"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - erunion
    labels:
      - scope:dependency
      - area:python
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
